// Version 3 Stage 1 Misty Lake — exact authored pixel matrices
// Governed by GitHub issue #16; base checkpoint 69d06766c0a6c165f26f71ded96d7b5bd8a122df.
// ART SOURCE ONLY. No runtime integration.
// One character = one logical pixel. '.' = transparent; other keys are existing index.html PAL entries.

const STAGE1_MISTY_LAKE = {
  baseline: {"repository":"raverx-dev/scarlet-moon-never-sets","issue":16,"branch":"sprite-redesign","checkpoint":"69d06766c0a6c165f26f71ded96d7b5bd8a122df","logical_canvas":"256x240","playfield":"192x240","hud":"64x240"},
  palette: {"r":"#e83a51","R":"#9a2438","w":"#fff0ce","W":"#d4c4a8","h":"#191528","H":"#2c2438","f":"#f6b993","F":"#e08a72","k":"#080810","b":"#424d9d","B":"#2a3160","c":"#81d8ed","C":"#c8f2ff","g":"#f5cb70","G":"#64b58a","p":"#ff93b4","P":"#c45a88","m":"#ae68d7","M":"#6b3d9a","y":"#ffe08a","s":"#c8c8d8","S":"#8a8aa0","u":"#704638","o":"#c47a4a","i":"#4aa0c8","n":"#171b39","e":"#21423e","d":"#3a2040","x":"#87243b","v":"#5a8f6a","l":"#d0e8ff","t":"#8b5a3c","a":"#a9a4b6","z":"#ffd0e0"},
  playfieldReference: { width: 192, height: 240, matrixFile: "lake_playfield_reference_192x240.txt", previewFile: "lake_playfield_reference_preview.png", centralSafeLane: [48,143] },
  assets: {
    lake_water_dark_a: { width: 8, height: 8, placement: "central-safe / anywhere" , role: "Primary low-contrast water base" , matrix: [
      "nnnnnnnn",
      "nnnBnnnn",
      "nBBnnnnn",
      "nnnnnnnn",
      "nnnnnBnn",
      "nnnBBnnn",
      "nnnnnnnn",
      "nBnnnnBn"
    ] },
    lake_water_dark_b: { width: 8, height: 8, placement: "central-safe / anywhere" , role: "Complementary low-contrast water base" , matrix: [
      "nnnnnnnn",
      "nnnnnBnn",
      "nnnBBnnn",
      "nnnnnnnn",
      "nBnnnnnn",
      "nnBBnnBn",
      "nnnnnnnn",
      "nnnnBnnn"
    ] },
    lake_water_dark_c: { width: 8, height: 8, placement: "central-safe / anywhere" , role: "Sparse low-contrast water base" , matrix: [
      "nnnnnnnn",
      "nBnnnnnn",
      "nnnBnnBn",
      "nnnnnnnn",
      "nnBBnnnn",
      "nnnnnBnn",
      "nBnnnnnn",
      "nnnnnnnn"
    ] },
    lake_water_edge_d: { width: 8, height: 8, placement: "edge columns / sparse" , role: "Slightly brighter water variant for side detail" , matrix: [
      "nnnnnnnn",
      "nnBBnnnn",
      "nnBbbBnn",
      "nnnnnnnn",
      "nnnnBBnn",
      "nBBbbBnn",
      "nnnnnnnn",
      "nnBnnnBn"
    ] },
    lake_ripple_dim_a: { width: 8, height: 8, placement: "central-safe / sparse overlay" , role: "Dim broken ripple" , matrix: [
      "........",
      "...B....",
      "..BBB...",
      "........",
      ".....B..",
      "...BB...",
      "........",
      "........"
    ] },
    lake_ripple_dim_b: { width: 8, height: 8, placement: "central-safe / sparse overlay" , role: "Offset dim broken ripple" , matrix: [
      "........",
      ".B......",
      ".BBB....",
      "........",
      "....BB..",
      "...B..B.",
      "........",
      "........"
    ] },
    lake_ripple_cool_a: { width: 8, height: 8, placement: "edge columns / upper field" , role: "Cool moonlit ripple" , matrix: [
      "........",
      "....B...",
      "..BbiB..",
      "...BB...",
      "........",
      ".BbbB...",
      "..B.....",
      "........"
    ] },
    lake_foam_spark_a: { width: 8, height: 8, placement: "edge columns only / rare" , role: "Tiny foam or ice-bright sparkle" , matrix: [
      "........",
      "........",
      "...l....",
      "..lCl...",
      "...l....",
      "........",
      "......l.",
      "........"
    ] },
    lake_foam_edge_b: { width: 8, height: 8, placement: "edge columns only / rare" , role: "Broken foam flecks with only two bright pixels" , matrix: [
      "........",
      "..B.....",
      ".BlB....",
      "..B.....",
      ".....B..",
      "....BlB.",
      ".....B..",
      "........"
    ] },
    lake_mist_wisp_a: { width: 8, height: 8, placement: "anywhere, low density; vertically phase-shift" , role: "Broken mist wisp; no continuous terrain line" , matrix: [
      "........",
      "..BB....",
      ".BbbB...",
      "...B....",
      ".....B..",
      "....Bbb.",
      "......B.",
      "........"
    ] },
    lake_mist_wisp_b: { width: 8, height: 8, placement: "anywhere, low density; alternate phase" , role: "Second broken mist wisp" , matrix: [
      "........",
      ".....B..",
      "...BbbB.",
      "..BB....",
      "........",
      ".B......",
      ".BbbB...",
      "...B...."
    ] },
    lake_mist_wisp_c: { width: 8, height: 8, placement: "central-safe / very sparse" , role: "Minimal mist fragment for bullet lane" , matrix: [
      "........",
      ".B......",
      "..bB....",
      "...B....",
      "......B.",
      "....Bbb.",
      ".....B..",
      "........"
    ] },
    lake_ice_glint: { width: 8, height: 8, placement: "edge columns only / rare" , role: "Restrained icy glint" , matrix: [
      "........",
      "...c....",
      "...l....",
      ".clClc..",
      "...l....",
      "...c....",
      "........",
      "........"
    ] },
    lake_moon_reflect_a: { width: 8, height: 8, placement: "upper/mid water, sparse and not during dense patterns" , role: "Fragmented silver moon reflection" , matrix: [
      "........",
      "...S....",
      "..SaS...",
      "...B....",
      "....S...",
      "...Sa...",
      "....B...",
      "........"
    ] },
    lake_moon_reflect_b: { width: 8, height: 8, placement: "upper/mid water, sparse alternate" , role: "Offset silver reflection fragment" , matrix: [
      "........",
      ".S......",
      "..aS....",
      "...B....",
      ".....S..",
      "....aS..",
      "...B....",
      "........"
    ] },
    lake_reeds_a: { width: 16, height: 16, placement: "left/right edge columns" , role: "Tall reed cluster, open silhouette" , matrix: [
      "................",
      "...........Gv...",
      ".......vG..v....",
      ".......e...v....",
      "...G...e...v....",
      "..vv...e.G.v....",
      "...v...e.G.vvG..",
      "...v...e.G.ve...",
      "...v...e.G.ve...",
      "...v..e..Gv.e...",
      "....vve..Ge.e...",
      "....v.e.Gvv..e..",
      "....v.e.G.v..e..",
      "....v.e.G.v..e..",
      "....veeeGeveee..",
      "..e.v.e.G.v.eee."
    ] },
    lake_reeds_b: { width: 16, height: 16, placement: "left/right edge columns" , role: "Complementary reed cluster" , matrix: [
      "................",
      "................",
      "................",
      ".........vG.....",
      ".....G...e......",
      ".....v...e.Gv...",
      "....vv...e.v....",
      "....ev.G.e.v....",
      "....ev.G.e..v...",
      "...e.v.G.e..e...",
      "...eev.G.ve.vv..",
      "...v.v.Ge.e.v...",
      "...e.v..G.e.v...",
      "..e..v..G.e..v..",
      "..e..v..G.e..v..",
      ".ee.ev.eG.ee.ve."
    ] },
    lake_shore_stone_a: { width: 16, height: 16, placement: "edge columns / shoreline" , role: "Blue-gray shoreline stone cluster" , matrix: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "........BSSSB...",
      ".......BSBaBSB..",
      "..SSSSBBBaBaBSB.",
      ".BaBSBBBBBBBBBB.",
      ".BBBBBBBaBBBBBB.",
      ".nnnnBBBBBBBaBB.",
      ".nnnnnBBBBBBBBB.",
      "..nnnnBBBBBBBBB.",
      "......BBBBBBBBB.",
      "..nnnnnnnnnnnnn.",
      "...e..e...e..e.."
    ] },
    lake_shore_stone_b: { width: 16, height: 16, placement: "edge columns / shoreline" , role: "Alternate staggered stone cluster" , matrix: [
      "................",
      "................",
      "................",
      "................",
      "..........S.....",
      ".......BBSBSBB..",
      "....S.BBSBBBSBB.",
      "..BSBSBBBaBBBBB.",
      ".BSBaBBBBBBaBBS.",
      ".BBBBBBBBBBBBSBB",
      "BBBBBBBBBBBBBBaB",
      ".BBBBBBBBBBBBBBB",
      ".BBBBBBBBBBBBBBB",
      "..BBBBBBBBBBBBBB",
      "....B.....B...B.",
      "e.e.e.e.e.e.e.e."
    ] },
    lake_lilypad_a: { width: 16, height: 16, placement: "edge water / rare" , role: "Optional edge lily pad; avoid central lane" , matrix: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "........e.......",
      ".....evvveee....",
      "...eeeeeeveeee..",
      "...eGeee..veee..",
      "..eeevee...eGe..",
      "...eeeveeeevee..",
      "...eeeeeveeeee..",
      ".....eeeeeee....",
      "................",
      "................",
      "................"
    ] },
    lake_shore_post: { width: 8, height: 24, placement: "edge columns only" , role: "Weathered shoreline post" , matrix: [
      "........",
      "..SSSS..",
      ".BBBBBB.",
      "..nnnn..",
      "..nuun..",
      "..nuun..",
      "..nuun..",
      "..noun..",
      "..nuun..",
      "..nuun..",
      "..nuun..",
      "..nuun..",
      "..nuun..",
      "..nuun..",
      "..noun..",
      "..nuun..",
      "..nuun..",
      "..nuun..",
      "..nuun..",
      "..nuun..",
      "..noun..",
      ".BBBBBB.",
      "b.b.b.b.",
      "..nnnn.."
    ] },
    lake_lantern_dim: { width: 16, height: 24, placement: "edge columns only; low frequency" , role: "Dim side lantern using dark red/orange, not bright bullet red" , matrix: [
      "................",
      ".....nnnnnn.....",
      "...RRRRRRRRRR...",
      "..nnnnnnnnnnnn..",
      "....RRRRRRRR....",
      "....RRRRRRRR....",
      "....R......R....",
      "....R.ogog.R....",
      "....R.gyyo.R....",
      "....R.ogog.R....",
      "....R.gogo.R....",
      "....R......R....",
      "....RRRRRRRR....",
      "......nnnn......",
      "......nuun......",
      "......nuun......",
      "......nuun......",
      "......nuun......",
      "......nuun......",
      "......nuun......",
      "......nuun......",
      "......nuun......",
      "......nuun......",
      ".....BBBBBB....."
    ] },
    lake_ice_shard: { width: 8, height: 16, placement: "edge water / rare accent" , role: "Small restrained ice shard" , matrix: [
      "........",
      "....l...",
      "...lC...",
      "...Cc...",
      "..cClc..",
      "..clCc..",
      ".BcClc..",
      "..BcCB..",
      "..BccB..",
      "...BcB..",
      "...Bc...",
      "...BB...",
      "...B....",
      "........",
      "........",
      "........"
    ] },
    lake_water_band_e: { width: 8, height: 8, placement: "anywhere / sparse horizontal current break" , role: "Minimal darker water-band overlay to break uniform open-water repetition" , matrix: [
      "........",
      "..BBB...",
      ".BBBBB..",
      "..BBBB..",
      "....BB..",
      "........",
      "..B.....",
      ".....B.."
    ] },
    lake_mist_transition_d: { width: 8, height: 8, placement: "upper/mid field / sparse broken bank" , role: "Denser broken mist transition overlay for larger drifting banks without forming platform terrain" , matrix: [
      "..BBB...",
      ".BSSBB..",
      "BSSaaBB.",
      ".BSSSSB.",
      "..BSSS..",
      "...BB...",
      "........",
      "........"
    ] },
    lake_edge_cluster_c: { width: 16, height: 16, placement: "left/right edge columns only" , role: "Combined shoreline cluster: low rock base plus open reeds for richer side composition with one placement" , matrix: [
      "................",
      "................",
      "......v.........",
      "......G...G.....",
      ".....GG...GG....",
      ".....G....v.....",
      "...v.G....G.....",
      "..GG.G..v.G.....",
      "..G..G..G.G.G...",
      ".GG..G..G.G.G...",
      ".G...G..G.GGG...",
      "BBBBBBBBBBBB....",
      "SSaaSSaaSSaS....",
      "...S....S.......",
      "..n.n..n.n......",
      "..n.n..n.n......"
    ] }
  }
};

if (typeof module !== "undefined") module.exports = STAGE1_MISTY_LAKE;
