// Version 3 Stage 2 Forest of Magic — exact native pixel matrices.
// Governing spec: raverx-dev/scarlet-moon-never-sets#16
// Base checkpoint: sprite-redesign @ 69d06766c0a6c165f26f71ded96d7b5bd8a122df
// Authoring-only source. Do not load at runtime without the separate integration pass.
// Uses existing game PAL letters + '.' only. No palette extension requested.

const FOREST_STAGE2_PALETTE_INVENTORY = {
  "B": "#2a3160",
  "G": "#64b58a",
  "H": "#2c2438",
  "M": "#6b3d9a",
  "R": "#9a2438",
  "W": "#d4c4a8",
  "b": "#424d9d",
  "e": "#21423e",
  "g": "#f5cb70",
  "h": "#191528",
  "i": "#4aa0c8",
  "m": "#ae68d7",
  "n": "#171b39",
  "o": "#c47a4a",
  "r": "#e83a51",
  "t": "#8b5a3c",
  "u": "#704638",
  "v": "#5a8f6a",
  "w": "#fff0ce",
  "y": "#ffe08a"
};

const FOREST_STAGE2_ASSETS = {
  // 8x8 | bark | side trunks | repeatable trunk bark
  forest_bark_a: [
    "uutuuutu",
    "utthuutu",
    "utuhuttu",
    "uuutttuu",
    "tuhuutut",
    "utuooutu",
    "uuthutuu",
    "tuutuutu",
  ],
  // 8x8 | bark | side trunks | alternate repeatable bark
  forest_bark_b: [
    "tuutuutu",
    "uuhuttuu",
    "uttootut",
    "uutthutu",
    "tutuuhuu",
    "uutottuu",
    "uhuututu",
    "utuutttu",
  ],
  // 8x8 | bark | side trunks only | knot/scar bark insert
  forest_bark_knot: [
    "uutttuuu",
    "utohottu",
    "uohohotu",
    "tohhhhot",
    "uohohotu",
    "utohottu",
    "uutttuuu",
    "utuututu",
  ],
  // 8x8 | foliage | edges | small leaf cluster
  forest_leaf_a: [
    "..ee....",
    ".evve...",
    "evGvve..",
    "eGGvvee.",
    ".evGve..",
    "..eve...",
    "...e....",
    "........",
  ],
  // 8x8 | foliage | edges | alternate leaf cluster
  forest_leaf_b: [
    "...e....",
    "..eve...",
    ".evGve..",
    "evvvGve.",
    "eGvGvve.",
    ".evvve..",
    "..ee....",
    "........",
  ],
  // 8x8 | foliage | edges | broken anti-repetition leaf cluster
  forest_leaf_c: [
    "........",
    ".ee.e...",
    "evvve.e.",
    "eGvGvve.",
    ".vvGve..",
    "..eve...",
    "...e....",
    "........",
  ],
  // 8x8 | foliage | far edges only | rare moonlit leaf accent
  forest_leaf_moonlit: [
    "....e...",
    "..evve..",
    ".evGvve.",
    "evvGivve",
    ".evGvve.",
    "..evve..",
    "...e....",
    "........",
  ],
  // 8x8 | ground | central lane | primary quiet bullet-lane ground
  forest_path_lane_a: [
    "nnnnhnnn",
    "nnnnnnnn",
    "nBnnnnnn",
    "nnnnHnnn",
    "nnnnnnnn",
    "hnnnnnnn",
    "nnnnnBnn",
    "nnnnnnnn",
  ],
  // 8x8 | ground | central lane | quiet lane alternate
  forest_path_lane_b: [
    "nnnnnnnn",
    "nnHnnnnn",
    "nnnnnnnn",
    "nnnnBnnn",
    "hnnnnnnn",
    "nnnnnnnn",
    "nnnnnHnn",
    "nnnnnnnn",
  ],
  // 8x8 | ground | central lane | quiet lane alternate 2
  forest_path_lane_c: [
    "nnnnBnnn",
    "nnnnnnnn",
    "nnHnnnnn",
    "nnnnnnnn",
    "nnnnnnnh",
    "nnnnnnnn",
    "nBnnnnnn",
    "nnnnHnnn",
  ],
  // 8x8 | ground | lane margins / sides | path-to-vegetation transition
  forest_ground_edge: [
    "nneennnn",
    "nevvennn",
    "nevGvenn",
    "nevvvenn",
    "nnennnnn",
    "nnnHnnnn",
    "nBnnennn",
    "nnnnnnnn",
  ],
  // 16x16 | canopy | side columns / top band | dense organic canopy metatile
  forest_canopy_a: [
    "..e...eve...e...",
    ".eve.eevee.eve..",
    "eeveeeGGveeevee.",
    "eGGvevGvvveGGvee",
    "vGvvvevnvevGvvve",
    "evvvveeveevvvvee",
    "eenvvvevevvvvee.",
    ".evvvveeevvvne..",
    "eevGGvvevGGvvee.",
    "evvGvvvvvGvvvvve",
    "eevvvvvevvvvveve",
    ".eevvveeevvveGnv",
    "..evvne.evvvvGvv",
    "...eve...eneevvv",
    "....e.....e.eeve",
    ".............eve",
  ],
  // 16x16 | canopy | side columns / top band | alternate organic canopy metatile
  forest_canopy_b: [
    "evee..e...eevee.",
    "GGveeeve.eeGGvee",
    "GvvvevvveevGvvve",
    "vvveevvveeevvvee",
    "eveevGGnveeevve.",
    "evevvGvvvveevvve",
    ".enevvvvveeevvve",
    "...eevvveeevnGvv",
    "...evvvveevvGvvv",
    "..evvvve.eevvvvv",
    ".eevvvee.evevvve",
    "eevGGvveeevevvne",
    "evvGvnvveGGveve.",
    "eevvvvvevGnvvee.",
    ".eevvveeevvvee..",
    "..evvve.eevee...",
  ],
  // 16x16 | canopy | upper outer edges | rare moonlit canopy highlight
  forest_canopy_moonlit: [
    "..e...eve...e...",
    ".eve.eevee.eve..",
    "eeveeeGiveeevee.",
    "eGivevGvvveGivee",
    "vGvvvevnvevGvvve",
    "evvvveeveevvvvee",
    "eenvvvevevvvvee.",
    ".evvvveeevvvne..",
    "eevGivvevGivvee.",
    "evvGvvvvvGvvvvve",
    "eevvvvvevvvvveve",
    ".eevvveeevvveGnv",
    "..evvne.evvvvGvv",
    "...eve...eneevvv",
    "....e.....e.eeve",
    ".............eve",
  ],
  // 16x16 | canopy | near lane margins / dim sections | low-contrast canopy mass
  forest_canopy_shadow: [
    "..n...nen...n...",
    ".nen.nnenn.nen..",
    "nnennnvvennnenn.",
    "nvveneveeenvvenn",
    "eveeeneneneveeen",
    "neeeennenneeeenn",
    "nnneeeneneeeenn.",
    ".neeeennneeenn..",
    "nnevveenevveenn.",
    "neeveeeeeveeeeen",
    "nneeeeeneeeeenen",
    ".nneeennneeenvne",
    "..neenn.neeeevee",
    "...nen...nnnneee",
    "....n.....n.nnen",
    ".............nen",
  ],
  // 16x16 | trunk | outer sides | straight trunk segment
  forest_trunk_straight: [
    ".....uttuuhu....",
    ".....uttuuhu....",
    ".....uttouhu....",
    ".....uttuohu....",
    ".....uttuuhu....",
    ".....uttuuhu....",
    ".....uthuuhu....",
    ".....utthuhu....",
    ".....uttuuhu....",
    ".....uttuuhu....",
    ".....uttuthu....",
    ".....uttuuhu....",
    ".....uttuuhu....",
    ".....uhtuuhu....",
    ".....uttuuhu....",
    ".....uttuuhu....",
  ],
  // 16x16 | trunk | outer sides | knotted trunk segment
  forest_trunk_knotted: [
    "....uttuuuhu....",
    "....uttuuuhu....",
    "....uttuuuhu....",
    "....uttuuuhu....",
    "....uttuuuhu....",
    "....uttoooou....",
    "....utoohhoo....",
    "....utohooho....",
    "....uttohhou....",
    "....uttuuuhu....",
    "....uttuuuhu....",
    "....uttuuuhu....",
    "....uttuuuhu....",
    "....uttuuuhu....",
    "....uttuuuhu....",
    "....uttuuuhu....",
  ],
  // 16x16 | trunk | outer left edge | left-spreading root flare
  forest_root_left: [
    ".........utuuh..",
    ".........utuuh..",
    ".........utuuh..",
    ".........utuuh..",
    ".........utuuh..",
    ".........utuuh..",
    ".........utuuh..",
    ".........utuuh..",
    ".........uuuuh..",
    "........uuhtuu..",
    "......uuuh.t.u..",
    "....uu.hhot...u.",
    "..uu..hu..t..ou.",
    "uu...ho..t.....u",
    "...hou...t.....u",
    "..h.u...t.......",
  ],
  // 16x16 | trunk | outer right edge | right-spreading root flare
  forest_root_right: [
    "..huutu.........",
    "..huutu.........",
    "..huutu.........",
    "..huutu.........",
    "..huutu.........",
    "..huutu.........",
    "..huutu.........",
    "..huutu.........",
    "..huuuu.........",
    "..uuthuu........",
    "..u.t.huuu......",
    ".u...tohh.uu....",
    ".uo..t..uh..uu..",
    "u.....t..oh...uu",
    "u.....t...uoh...",
    ".......t...u.h..",
  ],
  // 16x16 | mushroom | sides only | red spotted mushroom
  forest_mushroom_red: [
    "................",
    "................",
    "................",
    "....hrrrrrrh....",
    "..hrrwrrrwrrrh..",
    "..rrrrrrrrrrrr..",
    ".hrwrrrrrrrwrrh.",
    "..rrrrrwrrrrrr..",
    "...hRRRRRRRRh...",
    ".....hWwWWh.....",
    "......WwWW......",
    "......WwWW......",
    "......WwWW......",
    ".....hWWWWh.....",
    ".....hWWWWh.....",
    "................",
  ],
  // 16x16 | mushroom | sides only | violet spotted mushroom
  forest_mushroom_violet: [
    "................",
    "................",
    "................",
    "....hmmmmmmh....",
    "..hmmwmmmwmmmh..",
    "..mmmmmmmmmmmm..",
    ".hmwmmmmmmmwmmh.",
    "..mmmmmwmmmmmm..",
    "...hMMMMMMMMh...",
    ".....hWwWWh.....",
    "......WwWW......",
    "......WwWW......",
    "......WwWW......",
    ".....hWWWWh.....",
    ".....hWWWWh.....",
    "................",
  ],
  // 16x16 | mushroom | far sides only | small mixed mushroom cluster
  forest_mushroom_cluster: [
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".........mmm....",
    "........mwmmm...",
    "...rrr.mMmmmMm..",
    "..rwrrr...W.....",
    ".rRrrrRr..W.....",
    "....W......rrr..",
    "....W.....rwrrr.",
    ".....e...rRrrrRr",
    "..e.....e...W.e.",
    "............W...",
  ],
  // 8x16 | light | outer sides; sparse | small magical forest lantern
  forest_lantern_small: [
    "...uu...",
    "...uu...",
    "...uu...",
    ".RRRRRR.",
    "hRRRRRRh",
    "..rrrr..",
    ".hryyrh.",
    "..rwyr..",
    "..rygr..",
    "..ryyr..",
    ".hryyrh.",
    "..rrrr..",
    ".RRRRRR.",
    ".RRRRRR.",
    "...uu...",
    "...uu...",
  ],
  // 8x8 | light | outer edges only | single firefly sparkle
  forest_firefly_a: [
    "........",
    "........",
    "...g....",
    "..gyg...",
    "...g....",
    "........",
    "........",
    "........",
  ],
  // 8x8 | light | outer edges only | alternate firefly sparkle
  forest_firefly_b: [
    "........",
    "....g...",
    "...gy...",
    "..g.g...",
    "...g....",
    "........",
    "........",
    "........",
  ],
  // 8x8 | light | outer edges / scripted accent | rare magical wisp
  forest_wisp: [
    "........",
    "...m....",
    "..mgm...",
    "..gyg...",
    "...g....",
    "...e....",
    "..eee...",
    "........",
  ],
  // 16x16 | silhouette | upper scenery band | distant pine silhouette
  forest_distant_pines_a: [
    "................",
    ".......nnn......",
    ".......nnn......",
    "......nnnnn.....",
    "..nnn.nnBnn.....",
    "..nnnnnnBnnnnnn.",
    ".nnnnnnnBnnnnnn.",
    ".nnBnnnnBnnnnnnn",
    "nnnBnnnnBnnnnBnn",
    "nnnnnnnnBnnnnBnn",
    "nnnnnnnnBnnnnBnn",
    "nnnnnnnnBnnnnBnn",
    "nnnnnnnnBnnnnBnn",
    "nnnnnnnnnnnnnBnn",
    "nnnnnnnnnnnnnBnn",
    "...B....B....B..",
  ],
  // 16x16 | silhouette | upper scenery band | alternate distant pine silhouette
  forest_distant_pines_b: [
    "................",
    "......nnn.......",
    "......nnn.......",
    ".....nnnnn......",
    ".....nnBnn.nnn..",
    ".nnnnnnBnnnnnn..",
    ".nnnnnnBnnnnnnn.",
    "nnnnnnnBnnnnBnn.",
    "nnBnnnnBnnnnBnnn",
    "nnBnnnnBnnnnnnnn",
    "nnBnnnnBnnnnnnnn",
    "nnBnnnnBnnnnnnnn",
    "nnBnnnnBnnnnnnnn",
    "nnBnnnnnnnnnnnnn",
    "nnBnnnnnnnnnnnnn",
    "..B....B....B...",
  ],
  // 16x16 | silhouette | upper outer band | rare moonlit distant trees
  forest_distant_pines_moonlit: [
    "................",
    ".......BBB......",
    ".......BBB......",
    "......BBBBB.....",
    "..BBB.BBbBB.....",
    "..BBBBBBbBBBBBB.",
    ".BBBBBBBbBBBBBB.",
    ".BBbBBBBbBBBBBBB",
    "BBBbBBBBbBBBBbBB",
    "BBBBBBBBbBBBBbBB",
    "BBBBBBBBbBBBBbBB",
    "BBBBBBBBbBBBBbBB",
    "BBBBBBBBbBBBBbBB",
    "BBBBBBBBBBBBBbBB",
    "BBBBBBBBBBBBBbBB",
    "...b....b....b..",
  ],
  // 16x16 | vegetation | sides | fern edge detail
  forest_fern: [
    "................",
    "................",
    "................",
    "....v.....v.....",
    "...G.vvevv......",
    "..vv...v...Gv...",
    "....vv.e.vv.....",
    ".vG...vvv...vv..",
    "...vvv.e.vvv.G..",
    "..vv..vvv..vv...",
    "....Gv.e.vv.....",
    "...vv.vvv.Gv....",
    ".....vvevv......",
    ".......v........",
    ".......e........",
    "................",
  ],
  // 16x16 | vegetation | lane margins / sides | dark grass/sedge tuft
  forest_grass_tuft: [
    "................",
    "................",
    "................",
    "................",
    ".....e.e.e......",
    ".....e.e.e......",
    "......eveee.e...",
    "..e.e.eeeee.e...",
    "...ee.eeeeve.e..",
    "...eveeeee.ee...",
    "....ee.eeee.v...",
    ".....eeeeeee....",
    "......eeeee.....",
    "......eeee......",
    ".......eee......",
    "........e.......",
  ],
  // 16x16 | vegetation | upper side canopy | hanging vine element
  forest_vine_hanging: [
    "........e.......",
    "........e.......",
    ".......ve.......",
    ".....vv.e.......",
    "...Gv...v.......",
    "........evv.....",
    "......vve..vG...",
    "....vv..e.......",
    "..Gv...evv......",
    ".......e..vv....",
    ".......v....vG..",
    ".....vve........",
    "...Gv..ev.......",
    ".......e.vv.....",
    ".......e...vG...",
    ".......e........",
  ],
  // 16x16 | vegetation | sides | compact edge shrub
  forest_shrub: [
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....eeeeeee....",
    ".....evGvvve....",
    ".....evvvvGe....",
    ".eeeeevvvveeeee.",
    ".evvGevvvvevvve.",
    ".evvvevvvvevGve.",
    ".evvveGeeeevvve.",
    ".eneeeee.neeeen.",
    "................",
    "................",
  ],
  // 16x16 | ground | side / lane margin only | subdued path-border stone
  forest_path_edge_stone: [
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....BBBBBBBB....",
    "..BBHBBBHBBBBB..",
    ".BBBBBBBBBBHBBB.",
    ".BBhBBBBBBBBhBB.",
    "..BBBBHBBBHBBB..",
    "....BhBBBhBB....",
    "................",
    "................",
    "................",
  ],
};

const FOREST_STAGE2_META = {
  "forest_bark_a": {
    "width": 8,
    "height": 8,
    "category": "bark",
    "use": "repeatable trunk bark",
    "placement": "side trunks"
  },
  "forest_bark_b": {
    "width": 8,
    "height": 8,
    "category": "bark",
    "use": "alternate repeatable bark",
    "placement": "side trunks"
  },
  "forest_bark_knot": {
    "width": 8,
    "height": 8,
    "category": "bark",
    "use": "knot/scar bark insert",
    "placement": "side trunks only"
  },
  "forest_leaf_a": {
    "width": 8,
    "height": 8,
    "category": "foliage",
    "use": "small leaf cluster",
    "placement": "edges"
  },
  "forest_leaf_b": {
    "width": 8,
    "height": 8,
    "category": "foliage",
    "use": "alternate leaf cluster",
    "placement": "edges"
  },
  "forest_leaf_c": {
    "width": 8,
    "height": 8,
    "category": "foliage",
    "use": "broken anti-repetition leaf cluster",
    "placement": "edges"
  },
  "forest_leaf_moonlit": {
    "width": 8,
    "height": 8,
    "category": "foliage",
    "use": "rare moonlit leaf accent",
    "placement": "far edges only"
  },
  "forest_path_lane_a": {
    "width": 8,
    "height": 8,
    "category": "ground",
    "use": "primary quiet bullet-lane ground",
    "placement": "central lane"
  },
  "forest_path_lane_b": {
    "width": 8,
    "height": 8,
    "category": "ground",
    "use": "quiet lane alternate",
    "placement": "central lane"
  },
  "forest_path_lane_c": {
    "width": 8,
    "height": 8,
    "category": "ground",
    "use": "quiet lane alternate 2",
    "placement": "central lane"
  },
  "forest_ground_edge": {
    "width": 8,
    "height": 8,
    "category": "ground",
    "use": "path-to-vegetation transition",
    "placement": "lane margins / sides"
  },
  "forest_canopy_a": {
    "width": 16,
    "height": 16,
    "category": "canopy",
    "use": "dense organic canopy metatile",
    "placement": "side columns / top band"
  },
  "forest_canopy_b": {
    "width": 16,
    "height": 16,
    "category": "canopy",
    "use": "alternate organic canopy metatile",
    "placement": "side columns / top band"
  },
  "forest_canopy_moonlit": {
    "width": 16,
    "height": 16,
    "category": "canopy",
    "use": "rare moonlit canopy highlight",
    "placement": "upper outer edges"
  },
  "forest_canopy_shadow": {
    "width": 16,
    "height": 16,
    "category": "canopy",
    "use": "low-contrast canopy mass",
    "placement": "near lane margins / dim sections"
  },
  "forest_trunk_straight": {
    "width": 16,
    "height": 16,
    "category": "trunk",
    "use": "straight trunk segment",
    "placement": "outer sides"
  },
  "forest_trunk_knotted": {
    "width": 16,
    "height": 16,
    "category": "trunk",
    "use": "knotted trunk segment",
    "placement": "outer sides"
  },
  "forest_root_left": {
    "width": 16,
    "height": 16,
    "category": "trunk",
    "use": "left-spreading root flare",
    "placement": "outer left edge"
  },
  "forest_root_right": {
    "width": 16,
    "height": 16,
    "category": "trunk",
    "use": "right-spreading root flare",
    "placement": "outer right edge"
  },
  "forest_mushroom_red": {
    "width": 16,
    "height": 16,
    "category": "mushroom",
    "use": "red spotted mushroom",
    "placement": "sides only"
  },
  "forest_mushroom_violet": {
    "width": 16,
    "height": 16,
    "category": "mushroom",
    "use": "violet spotted mushroom",
    "placement": "sides only"
  },
  "forest_mushroom_cluster": {
    "width": 16,
    "height": 16,
    "category": "mushroom",
    "use": "small mixed mushroom cluster",
    "placement": "far sides only"
  },
  "forest_lantern_small": {
    "width": 8,
    "height": 16,
    "category": "light",
    "use": "small magical forest lantern",
    "placement": "outer sides; sparse"
  },
  "forest_firefly_a": {
    "width": 8,
    "height": 8,
    "category": "light",
    "use": "single firefly sparkle",
    "placement": "outer edges only"
  },
  "forest_firefly_b": {
    "width": 8,
    "height": 8,
    "category": "light",
    "use": "alternate firefly sparkle",
    "placement": "outer edges only"
  },
  "forest_wisp": {
    "width": 8,
    "height": 8,
    "category": "light",
    "use": "rare magical wisp",
    "placement": "outer edges / scripted accent"
  },
  "forest_distant_pines_a": {
    "width": 16,
    "height": 16,
    "category": "silhouette",
    "use": "distant pine silhouette",
    "placement": "upper scenery band"
  },
  "forest_distant_pines_b": {
    "width": 16,
    "height": 16,
    "category": "silhouette",
    "use": "alternate distant pine silhouette",
    "placement": "upper scenery band"
  },
  "forest_distant_pines_moonlit": {
    "width": 16,
    "height": 16,
    "category": "silhouette",
    "use": "rare moonlit distant trees",
    "placement": "upper outer band"
  },
  "forest_fern": {
    "width": 16,
    "height": 16,
    "category": "vegetation",
    "use": "fern edge detail",
    "placement": "sides"
  },
  "forest_grass_tuft": {
    "width": 16,
    "height": 16,
    "category": "vegetation",
    "use": "dark grass/sedge tuft",
    "placement": "lane margins / sides"
  },
  "forest_vine_hanging": {
    "width": 16,
    "height": 16,
    "category": "vegetation",
    "use": "hanging vine element",
    "placement": "upper side canopy"
  },
  "forest_shrub": {
    "width": 16,
    "height": 16,
    "category": "vegetation",
    "use": "compact edge shrub",
    "placement": "sides"
  },
  "forest_path_edge_stone": {
    "width": 16,
    "height": 16,
    "category": "ground",
    "use": "subdued path-border stone",
    "placement": "side / lane margin only"
  }
};
