'use strict';

module.exports = Object.freeze({
  mansion_window_gothic_a: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '................',
    '.......SS.......',
    '......SbbS......',
    '...S.SB..BS.S...',
    '..HSSkkkHkkSSH..',
    '..HSSkBBHbkSSH..',
    '..HSSkBBHbkSSH..',
    '..HSSkBBHbkSSH..',
    '..HSSHHHHHHSSH..',
    '..HSSkbbHBkSSH..',
    '..HSSkbbHBkSSH..',
    '..HSSkbbHBkSSH..',
    '..HSSHHHHHHSSH..',
    '..HSSkBBHbkSSH..',
    '..HSSkBBHbkSSH..',
    '..HSSkkkHkkSSH..',
  ]) }),
  mansion_window_gothic_b: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '................',
    '.......SS.......',
    '......SbbS......',
    '...S.SB..BS.S...',
    '..HSSkkkHkkSSH..',
    '..HSSkBBHbkSSH..',
    '..HSSkBllbkSSH..',
    '..HSSkBBHbkSSH..',
    '..HSSHHHHHHSSH..',
    '..HSSkbbHBkSSH..',
    '..HSSkxdHdkSSH..',
    '..HSSkdxHxkSSH..',
    '..HSSHHHHHHSSH..',
    '..HSSkdxHxkSSH..',
    '..HSSkxdHdkSSH..',
    '..HSSkkkHkkSSH..',
  ]) }),
  mansion_sconce_single: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '................',
    '........r.......',
    '.......yWy......',
    '........W.......',
    '........W.......',
    '........W.......',
    '.....y..g.......',
    '......gggu......',
    '.......ugu......',
    '.......ugu......',
    '.......ugu......',
    '.......uuu......',
    '.......uuu......',
    '................',
    '................',
    '................',
  ]) }),
  mansion_sconce_double: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '................',
    '................',
    '....r......r....',
    '...gyg....gyg...',
    '....W......W....',
    '....W......W....',
    '....W......W....',
    '....WgyuuygW....',
    '......uggu......',
    '......uggu......',
    '......uggu......',
    '......uggu......',
    '......uttu......',
    '................',
    '................',
    '................',
  ]) }),
  mansion_pillar_cap: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '.....HHHHHH.....',
    '.....HHHHHH.....',
    '....BBBBBBBB....',
    '....BBBBBBBB....',
    '...SSSSSSSSSS...',
    '..HSSSSSSSSSSH..',
    '..HHHHHHHHHHHH..',
    '..HHHHHHHHHHHH..',
    '..gggggggggggg..',
    '....uuuuuuuu....',
    '.....HSSHHH.....',
    '.....HSSHHH.....',
    '.....HSSHHH.....',
    '.....HSSHHH.....',
    '.....HSSHHH.....',
    '.....HSSHHH.....',
  ]) }),
  mansion_pillar_mid: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '....HSSBBBBh....',
    '....HSSBBBBh....',
    '....HSSBBBBh....',
    '....HSsBBHBh....',
    '....HSSBBBBh....',
    '....HSSBBBBh....',
    '....HSSBBBBh....',
    '....HSSBBBBh....',
    '....HSsBBHBh....',
    '....HSSBBBBh....',
    '....HSSBBBBh....',
    '....HSSBBBBh....',
    '....HSSBBBBh....',
    '....HSsBBHBh....',
    '....HSSBBBBh....',
    '....HSSBBBBh....',
  ]) }),
  mansion_pillar_base: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '.....HSSHHH.....',
    '.....HSSHHH.....',
    '.....HSSHHH.....',
    '.....HSSHHH.....',
    '.....HSSHHH.....',
    '.....HSSHHH.....',
    '.....HSSHHH.....',
    '....BBBBBBBB....',
    '....BBBBBBBB....',
    '....BBBBBBBB....',
    '...HHHHHHHHHH...',
    '...HHHHHHHHHH...',
    '...uuuuuuuuuu...',
    '..SSSSSSSSSSSS..',
    '..SSSSSSSSSSSS..',
    '..SSSSSSSSSSSS..',
  ]) }),
  mansion_railing: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '................',
    '.g...g....g...g.',
    'uuuuuuuuuuuuuuuu',
    'gggggggggggggggg',
    '.t...t....t...t.',
    '.g...g....g...g.',
    '.t...t....t...t.',
    '.t...t....t...t.',
    '.t...t....t...t.',
    '.t...t....t...t.',
    '.H...H....H...H.',
    '.t...t....t...t.',
    '.t...t....t...t.',
    'HHHHHHHHHHHHHHHH',
    'uuuuuuuuuuuuuuuu',
    '................',
  ]) }),
  mansion_door_arch_l: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '............HHHH',
    '........HHHHtttt',
    '......SS.ttt....',
    '.....S.uu.......',
    '....S.u.........',
    '....Su..........',
    '..HS.u..........',
    '..HSu...........',
    '..HSu...........',
    '..Hgu...........',
    '..HSu...........',
    '..HSu...........',
    '..HSu...........',
    '..Hgu...........',
    '..HSu...........',
    '..HSu...........',
  ]) }),
  mansion_door_arch_r: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    'HHHH............',
    'ttttHHHH........',
    '....ttt.SS......',
    '.......uu.S.....',
    '.........u.S....',
    '..........uS....',
    '..........u.SH..',
    '...........uSH..',
    '...........uSH..',
    '...........ugH..',
    '...........uSH..',
    '...........uSH..',
    '...........uSH..',
    '...........ugH..',
    '...........uSH..',
    '...........uSH..',
  ]) }),
  mansion_door_side_l: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '..HSSHu.........',
    '..HSSHu.........',
    '..HSSHu.........',
    '..HSgHu.........',
    '..HSSHu.........',
    '..HSSHu.........',
    '..HSSHu.........',
    '..HSSHu.........',
    '..HSSHu.........',
    '..HSgHu.........',
    '..HSSHu.........',
    '..HSSHu.........',
    '..HSSHu.........',
    '..HSSHu.........',
    '..HSgHu.........',
    '..HSSHu.........',
  ]) }),
  mansion_door_side_r: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '.........uHSSH..',
    '.........uHSSH..',
    '.........uHSSH..',
    '.........uHgSH..',
    '.........uHSSH..',
    '.........uHSSH..',
    '.........uHSSH..',
    '.........uHSSH..',
    '.........uHSSH..',
    '.........uHgSH..',
    '.........uHSSH..',
    '.........uHSSH..',
    '.........uHSSH..',
    '.........uHSSH..',
    '.........uHgSH..',
    '.........uHSSH..',
  ]) }),
  mansion_door_panel: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    'kkhhhhhhhhhhhhkk',
    'kkhnnnnnnnnnnhkk',
    'kkhnnnnnnnnnnhkk',
    'kkhnnHHHdHHnnhkk',
    'kkhnnHHHdHHnnhkk',
    'kkhnnHHHdHHnnhkk',
    'kkhnnHHHdHHnnhkk',
    'kkhnnddddddnnhkk',
    'kkhnnHHHdHHnnhkk',
    'kkhnnHHHdHgnnhkk',
    'kkhnnHHHdHHnnhkk',
    'kkhnnHHHdHHnnhkk',
    'kkhnnHHHdHHnnhkk',
    'kkhnnHHHdHHnnhkk',
    'kkhnnnnnnnnnnhkk',
    'kkhnnnnnnnnnnhkk',
  ]) }),
  mansion_corridor_shadow: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    'HkkkkkkkkkkkkkkH',
    'HkkkkkkkkkkkkkkH',
    'HkkkkkkkkkkkkkkH',
    'HkkkkkkkkkkkkkkH',
    'HhhhhhhhhhhhhhhH',
    'HhhhhhhhhhhhhhhH',
    'HhhhhhhhhhhhhhhH',
    'HhhhhhhhhhhhhhhH',
    'HnnnnnnnnnnnnnnH',
    'HnnnnnnnnnnnnnnH',
    'HnnnnnnnnnnnnnnH',
    'HnnnnnnnnnnnnnnH',
    'HHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHH',
    'HHHHHHHHHHHHHHHH',
  ]) }),
  mansion_corridor_threshold: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    'nnHnnnnnnnnnnHnn',
    'nnHnnnnnnnnnnHnn',
    'HHHHHHHHHHHHHHHH',
    'SSHSSSSSSSSSSHSS',
    'nnHnnnnnnnnnnHnn',
    'nnHnnnnnnnnnnHnn',
    'uuHuuuuuuuuuuHuu',
    'ttHttttttttttHtt',
    'nnHnnnnnnnnnnHnn',
    'nnHnnnnnnnnnnHnn',
    'xxHxxxxxxxxxxHxx',
    'RRHRRRRRRRRRRHRR',
    'nnHnnnnnnnnnnHnn',
    'nnHnnnnnnnnnnHnn',
    'hhHhhhhhhhhhhHhh',
    'nnHnnnnnnnnnnHnn',
  ]) }),
});
