'use strict';

module.exports = Object.freeze({
  mansion_painting_frame: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '................',
    '..uuuuuuuuuuuu..',
    '..uggggggggggu..',
    '..ugykkkkkkygu..',
    '..ugkkkkkkkkgu..',
    '..ugkkkHHkkkgu..',
    '..ugkkkHHkkkgu..',
    '..ugkkkHHkkkgu..',
    '..ugkkddddkkgu..',
    '..ugkkddddkkgu..',
    '..ugkxddddxkgu..',
    '..ugkkkkkkkkgu..',
    '..ugtkkkkkktgu..',
    '..uggggggggggu..',
    '..uuuuuuuuuuuu..',
    '................',
  ]) }),
  mansion_bookcase: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '................',
    '.uuuuuuuuuuuuuu.',
    '.ukkkBkkkSkkkku.',
    '.ukxkBkRkSkdkku.',
    '.ukxkBkRkSkdkku.',
    '.ukkkkkkkkkkkku.',
    '.uttttttttttttu.',
    '.ukBkkkkgkRkkku.',
    '.ukBkkxkkkRkSku.',
    '.ukBkkxkkkRkSku.',
    '.ukkkkkkkkkkkku.',
    '.uttttttttttttu.',
    '.ukdkBkxkkSkgku.',
    '.ukdkBkxkkSkkku.',
    '.uuuuuuxuuuuuuu.',
    '.HHHHHHHHHHHHHH.',
  ]) }),
  mansion_side_table: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..gggggggggggg..',
    '...uuuuuuuuuu...',
    '....uuuuuuuu....',
    '....uuHuuHuu....',
    '....uuuuuuuu....',
    '.....t....t.....',
    '.....t....t.....',
    '.....t....t.....',
    '.....t....t.....',
  ]) }),
  mansion_vase_flowers: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '................',
    '................',
    '......rrRR......',
    '..........xx....',
    '.......RR.......',
    '.....rreerr.....',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '......BBBB......',
    '.....bbbbbb.....',
    '......BBBB......',
    '......BBBB......',
    '......BBBB......',
    '......HHHH......',
    '................',
  ]) }),
  mansion_bust_statue: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '................',
    '................',
    '................',
    '................',
    '.......ss.......',
    '......a..a......',
    '......aaaa......',
    '.....SaHHaS.....',
    '......aaaa......',
    '......aaSa......',
    '....ssaaaass....',
    '.....SSSSSS.....',
    '.....SSSSSS.....',
    '.....SSSSSS.....',
    '.....SSSSSS.....',
    '.....HHHHHH.....',
  ]) }),
  mansion_drape_banner: Object.freeze({ width: 16, height: 16, pixels: Object.freeze([
    '................',
    '...gggggggggg...',
    '....RRRRRRRR....',
    '....xRxxxxdx....',
    '....xRxxxxdx....',
    '....xRxxxxdx....',
    '....xRxkkxdx....',
    '....xRkxxkdx....',
    '....xkxkkxkx....',
    '....xRxkkxdx....',
    '....xRxxxxdx....',
    '....xRxxxxdx....',
    '....xRxxxxdx....',
    '....x.x..x.x....',
    '.....x....x.....',
    '................',
  ]) }),
});
