'use strict';

module.exports = Object.freeze({
  mansion_wall_plain: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    'hhhhhhhh',
    'nnnnnnnH',
    'nHnnnnnn',
    'nnnHnnnn',
    'hhhhhhhh',
    'nnnnnnnn',
    'nnnnnHnn',
    'nnnnnnnn',
  ]) }),
  mansion_wall_damask_a: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    'nnnddnnn',
    'nnHxxHnn',
    'nHxRRxHn',
    'nnHxxHnn',
    'nnnddnnn',
    'nnHxxHnn',
    'nHxRRxHn',
    'nnnddnnn',
  ]) }),
  mansion_wall_damask_b: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    'hdhhhhdh',
    'HxHhhHxH',
    'hHRHHRHh',
    'hhxddxhh',
    'hdhhhhdh',
    'HxHhhHxH',
    'hHRHHRHh',
    'hhxddxhh',
  ]) }),
  mansion_wall_panel: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    'HHHHHHHh',
    'Hnnnnnnh',
    'Hnddddnh',
    'HndHhhnh',
    'HndhHhnh',
    'Hndhhhnh',
    'Hnnnnnnh',
    'Hhhhhhhh',
  ]) }),
  mansion_carpet_center: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    'dddddddd',
    'dhdddddd',
    'ddddddhd',
    'dddddddd',
    'dddddddd',
    'dddddhdd',
    'ddhddddd',
    'dddddddd',
  ]) }),
  mansion_carpet_motif: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    'dddxxddd',
    'ddxddxdd',
    'dRddddRd',
    'ddxRRxdd',
    'ddxRRxdd',
    'dRddddRd',
    'ddxddxdd',
    'dddxxddd',
  ]) }),
  mansion_carpet_edge_l: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    'xxRHdddd',
    'xrRHdddd',
    'xxRHdddd',
    'xxRHdddd',
    'xxRHdddd',
    'xrRHdddd',
    'xxRHdddd',
    'xxRHdddd',
  ]) }),
  mansion_carpet_edge_r: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    'ddddHRxx',
    'ddddHRxx',
    'ddddHRrx',
    'ddddHRxx',
    'ddddHRxx',
    'ddddHRxx',
    'ddddHRrx',
    'ddddHRxx',
  ]) }),
  mansion_floor_wood: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    'tttttttt',
    'uuoHuuuu',
    'uuuuuuou',
    'Huuouuuu',
    'tttttttt',
    'uouuHuuu',
    'uuuuuouu',
    'uuuuuuuo',
  ]) }),
  mansion_floor_stone: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    'SSSHSSSS',
    'BBBHBBBB',
    'BSBHBSBB',
    'BBBHBBBB',
    'HHHHHHHH',
    'BBBBBBHB',
    'BBSBBBHS',
    'BBBBBBHB',
  ]) }),
  mansion_molding_horizontal: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    '........',
    'HHHHHHHH',
    'SgSSSSgS',
    'uuuuuuuu',
    'tttttttt',
    'HHHHHHHH',
    '........',
    '........',
  ]) }),
  mansion_trim_vertical: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    '..HSut..',
    '..Hgut..',
    '..HSut..',
    '..HSut..',
    '..HSut..',
    '..HSut..',
    '..Hgut..',
    '..HSut..',
  ]) }),
  mansion_masonry_shadow: Object.freeze({ width: 8, height: 8, pixels: Object.freeze([
    'HHHHHHHH',
    'hhxhhhhh',
    'hdhhhdhh',
    'hhhhhhhh',
    'HHHHHHHH',
    'hhhhhhxh',
    'hhhhxhhh',
    'hhhhhhhh',
  ]) }),
});
