// Approved native logical-pixel matrices. Integration source only; do not load at runtime.
// Uses existing index.html PAL letters; '.' is transparent.
const SUPPORT_SPRITE_REDIRECTION = {
  meilingSleep: [
    "........................",
    "........................",
    "........................",
    "..hevvvFe...............",
    "..FFRrrRHh..............",
    ".RFFrrrrrr.....evveee...",
    "HvRRrrrRrRrRRHevvvvevv..",
    "heFRFRRHRRRvWveevvveHvv.",
    ".RrRfgvvRRRwwweHeevvevWv",
    ".RRRFWWfRHRvWWe.eeevvvvG",
    "hRRHeWffHHRHevfeeHHHeevW",
    "rRrRHFFFffHHFWge.eWvvvWv",
    "HHH...heeH..vFH...HeHeH.",
    "........................",
    "........................",
    "........................"
  ],
  fairyIce: [
    "...ibhhH........",
    "...bbHbbbbH.....",
    ".bHhbbiccccB.i..",
    ".lcBHbciiiihcl..",
    ".WbBHbibWiHHbi..",
    ".BcbBBbWfwbBi...",
    "...BBhbBbbhB....",
    "...hbFWbbbbWH...",
    "...cbBBbbbHbh...",
    "..BlBhbibib.....",
    "..h...BiiFH.....",
    "......bF.b......",
    "......b.........",
    "................",
    "......H.........",
    ".BHB.BbhHBbBH..."
  ],
  fairyMagic: [
    ".........HMH....",
    ".....HFFHMFFFH..",
    ".....hFmMfyfff..",
    ".....MfFMFFFFF..",
    "......FhMFFFFM..",
    ".....MMHHFfyyM..",
    ".....mWWGHMFM...",
    "......MGMWFFMM..",
    ".......MmMFFFH..",
    "......FmMFFFFF..",
    ".....MWM.MfFFM..",
    ".....H...HM.m...",
    ".........HH.....",
    "................",
    "............H...",
    "..GGHHHHHM.MHh.."
  ],
  fairyMansion: [
    ".........dMM....",
    ".........mMM....",
    ".....MpdddPP....",
    ".....MWwMMMM....",
    "......mFdMMP....",
    "......HmMdMF....",
    "........ddMM....",
    ".......mpMWM....",
    "......FfPdMM....",
    "......ddhdPP....",
    "........M.PP....",
    "..........Md....",
    "..........M.....",
    "................",
    "................",
    "...mM.HMHHHH...."
  ]
};
