// Approved native logical-pixel matrices. Integration source only; do not load at runtime.
// Uses existing index.html PAL letters; '.' is transparent.
const SUPPORT_SPRITE_REDIRECTION = {
  meilingSleep: [
    "........................",
    "........................",
    "........................",
    "..hevvvFe...............",
    "..FFRrrRHh..............",
    ".RFFrrrrrr.....evveee...",
    "HvRRrrrRrRrRRHevvvvevv..",
    "heFRFRRHRRRvWveevvveHvv.",
    ".RrRfgvvRRRwwweHeevvevWv",
    ".RRRFWWfRHRvWWe.eeevvvvG",
    "hRRHeWffHHRHevfeeHHHeevW",
    "rRrRHFFFffHHFWge.eWvvvWv",
    "HHH...heeH..vFH...HeHeH.",
    "........................",
    "........................",
    "........................"
  ],
  fairyIce: [
    "...ibhhH........",
    "...bbHbbbbH.....",
    ".bHhbbiccccB.i..",
    ".lcBHbciiiihcl..",
    ".WbBHbibWiHHbi..",
    ".BcbBBbWfwbBi...",
    "...BBhbBbbhB....",
    "...hbFWbbbbWH...",
    "...cbBBbbbHbh...",
    "..BlBhbibib.....",
    "..h...BiiFH.....",
    "......bF.b......",
    "......b.........",
    "................",
    "................",
    "................"
  ],
  fairyMagic: [
    ".........HMH....",
    ".....HFFHMFFFH..",
    ".....hFmMfyfff..",
    ".....MfFMFFFFF..",
    "......FhMFFFFM..",
    ".....MMHHFfyyM..",
    ".....mWWGHMFM...",
    "......MGMWFFMM..",
    ".......MmMFFFH..",
    "......FmMFFFFF..",
    ".....MWM.MfFFM..",
    ".....H...HM.m...",
    ".........HH.....",
    "................",
    "................",
    "................"
  ],
  fairyMansion: [
    "......mPm.......",
    "...m..MMM..m....",
    "..mM.MMMMM.Mm...",
    ".mMM.MffffM.MMm.",
    "..M..FfkfF..M...",
    ".mM..Fffff..Mm..",
    "..M...PwwP...M..",
    ".mM..PPPPPP..Mm.",
    "..M..PPMMPP..M..",
    ".mM.PPPPPPPP.Mm.",
    "..M.PPPPPPPP.M..",
    "...PP......PP...",
    "....F......F....",
    "....M......M....",
    "...MM......MM...",
    "................"
  ]
};
