const inspection=document.createElement('div');
inspection.innerHTML='<h3>Acceptance inspection</h3><label>Scene <select id="audit-scene"></select></label><label>Tick <input id="audit-tick" type="number" value="120"></label><button id="audit-jump">Inspect frozen frame</button><button id="audit-next">Advance dialogue</button><button id="audit-motion">Resume motion</button><button id="audit-freeze">Freeze motion</button><pre id="audit-meta"></pre>';
panel.prepend(inspection);
const cases=['boot','notice','title','how','attract','stage1','stage2','stage3','stagecard:1','stagecard:2','stagecard:3','gate','dawn','endingScene','endingExit','theend','credits','final','continue',...Object.keys(DIALOGUE).map(x=>'dialogue:'+x),...Object.entries(PHASES).flatMap(([w,ps])=>ps.map((p,i)=>'boss:'+w+':'+i))];
for(const v of cases){let o=document.createElement('option');o.value=o.textContent=v;document.querySelector('#audit-scene').append(o)}
let auditFrozen=false;
const originalTick=tick;tick=function(){if(!auditFrozen)originalTick()};
function auditMeta(){document.querySelector('#audit-meta').textContent=JSON.stringify({state,stateTick,stage,stageTick,phase:boss?.data?.id,bossTick:boss?.t,bullets:bullets.length,dialogue:dialogue?.id,line:dialogue?.index,frame},null,2)}
document.querySelector('#audit-jump').onclick=()=>{auditFrozen=false;paused=false;for(const k in keys)keys[k]=false;pressed={};newRun();clearField();boss=null;dialogue=null;phaseGap=0;const v=document.querySelector('#audit-scene').value;frame=0;let n=+document.querySelector('#audit-tick').value; if(v.startsWith('boss:')){const[,who,p]=v.split(':');stage=who==='cirno'?1:who==='marisa'?2:3;startBoss(who);boss.phase=+p;beginPhase();phaseGap=0;}else if(v.startsWith('dialogue:')){const id=v.slice(9);stage=id.startsWith('cirno')?1:id.startsWith('marisa')?2:3;showDialogue(id,()=>toTitle(),id==='intro'?'shrine':id==='ending'?'morning':id.startsWith('remilia')?'roof':'');}else if(v.startsWith('stagecard:')){startStage(+v.slice(10));setState('stagecard');}else if(v.startsWith('stage')){startStage(+v.slice(5));setState('play');if(stage===3&&n>2520)sakuyaDone=true;}else setState(v);for(let i=0;i<n;i++){player.inv=999;tick()}if(dialogue)dialogue.print=999;auditFrozen=true;draw();auditMeta();};
document.querySelector('#audit-next').onclick=()=>{auditFrozen=false;pressed.z=true;tick();if(dialogue)dialogue.print=999;auditFrozen=true;draw();auditMeta()};
document.querySelector('#audit-motion').onclick=()=>{auditFrozen=false;canvas.focus()};
document.querySelector('#audit-freeze').onclick=()=>{auditFrozen=true;draw();auditMeta()};
// Regression owns synchronous simulation while running; inspection freeze must not block it.
const originalRun=QA.run;QA.run=function(){auditFrozen=false;return originalRun.call(this)};
const diag=document.createElement('button');diag.textContent='Run acceptance diagnostics';inspection.append(diag);const dout=document.createElement('pre');dout.id='audit-diagnostics';inspection.append(dout);
diag.onclick=()=>{auditFrozen=false;paused=false;for(const k in keys)keys[k]=false;pressed={};const out={music:Object.fromEntries(Object.entries(SONGS).map(([k,v])=>{const dt=60/v.bpm/4;return [k,{bpm:v.bpm,form:v.form,loopFrom:v.loopFrom,steps:v.totalSteps,loopStartStep:v.loopStart,seconds:+(v.totalSteps*dt).toFixed(2),loopSeconds:+((v.totalSteps-v.loopStart)*dt).toFixed(2),voices:['p1','p2','tri','noi'],source:v.source||''}]}))};
newRun();stage=2;startBoss('marisa');phaseGap=0;for(let i=0;i<70;i++){player.inv=999;tick()}out.m1CurvedStars=bullets.filter(b=>b.shape==='star'&&b.curve).length;
newRun();stage=3;sakuyaDone=true;checkpoint='stage';continueRun();setState('play');for(let i=0;i<2521;i++){player.inv=999;tick()}out.stage3ContinueAfterSakuya={state,stageTick,sakuyaDone,boss:boss?.who||null};
newRun();stage=3;startBoss('remilia');boss.phase=4;beginPhase();phaseGap=0;let max=0,on=0,lastMin=999,lastMax=0;for(let i=0;i<2040;i++){player.inv=999;tick();const visible=bullets.filter(b=>b.x>=0&&b.x<192&&b.y>=0&&b.y<240).length;max=Math.max(max,bullets.length);on=Math.max(on,visible);if(i>=1500&&i<2039){lastMin=Math.min(lastMin,visible);lastMax=Math.max(lastMax,visible)}}out.r5Density={maxAllocated:max,maxCentersOnscreen:on,lastNineSecondsVisibleRange:[lastMin,lastMax]};
newRun();startBoss('marisa');boss.phase=2;beginPhase();phaseGap=0;for(let i=0;i<110;i++){player.inv=999;tick()}out.laserOriginOffset=lasers.map(l=>({age:l.age,distanceFromBoss:Math.hypot(l.x-boss.x,l.y-boss.y)}));
newRun();startBoss('cirno');phaseGap=0;player.inv=0;player.x=boss.x;player.y=boss.y;tick();out.bossContact={deathWindow:player.death,lives:player.lives};
out.dialogue=Object.fromEntries(Object.entries(DIALOGUE).map(([k,v])=>[k,{lines:v.length,maxWrappedLines:Math.max(...v.map(x=>wrap(x[1],32).length))}]));
newRun();stage=2;startBoss('marisa');boss.phase=3;beginPhase();phaseGap=0;for(let i=0;i<125;i++){player.inv=999;tick()}out.sparkGeometry=lasers.map(l=>({angle:l.a,declaredWidth:l.width,paintedPerpendicularWidth:l.width*(Math.abs(Math.sin(l.a))+Math.abs(Math.cos(l.a))),collisionWidth:l.width+3}));
dout.textContent=JSON.stringify(out,null,2);auditFrozen=true;draw();auditMeta();};
const aud=document.createElement('div');aud.innerHTML='<label>Music inspection <select id="audit-music"></select></label><button id="audit-audio">Play music without combat</button><label>Effect inspection <select id="audit-effect"></select></label><button id="audit-sound">Play effect</button>';inspection.append(aud);for(const [id,obj]of [['audit-music',SONGS],['audit-effect',SFX]])for(const k of Object.keys(obj)){const o=document.createElement('option');o.value=o.textContent=k;document.getElementById(id).append(o)}document.getElementById('audit-audio').onclick=()=>{audioInit();paused=false;boss=null;music(document.getElementById('audit-music').value)};document.getElementById('audit-sound').onclick=()=>{audioInit();sound(document.getElementById('audit-effect').value)};
